DROP TABLE PIC_TB;
DROP SEQUENCE pic_seq;
DROP TABLE TAG_TB;
DROP SEQUENCE tag_seq;
DROP TABLE LINK_TB;
DROP SEQUENCE link_seq;
DROP TABLE LB_REPLE;
DROP SEQUENCE lb_reple_seq;
DROP TABLE LOOKBOOK_BOARD;
DROP SEQUENCE lb_seq;
DROP SEQUENCE lb_seq2;
DROP TABLE FB_REPLE;
DROP SEQUENCE fb_reple_seq;
DROP TABLE FREE_BOARD;
DROP SEQUENCE fb_seq;
DROP TABLE MEMBER_TB;


CREATE TABLE MEMBER_TB(
 user_id VARCHAR2(50) PRIMARY KEY
 , user_pw VARCHAR2(50) NOT NULL
 , user_name VARCHAR2(50) NOT NULL
 , user_state NUMBER DEFAULT 0
 , user_regdate DATE DEFAULT SYSDATE
 , link_hits NUMBER DEFAULT 0
);

CREATE SEQUENCE fb_seq;

CREATE TABLE FREE_BOARD(
 fb_boardnum NUMBER PRIMARY KEY
 , user_id VARCHAR2(50) CONSTRAINT fb_id_fk REFERENCES MEMBER_TB(user_id)
 , fb_title VARCHAR2(100) NOT NULL
 , fb_content VARCHAR2(2000) NOT NULL
 , fb_likes NUMBER DEFAULT 0
 , fb_hitcount NUMBER DEFAULT 0
 , fb_regdate DATE DEFAULT SYSDATE
);

CREATE SEQUENCE fb_reple_seq;

CREATE TABLE FB_REPLE(
 fb_reple_num NUMBER PRIMARY KEY
 , fb_boardnum NUMBER CONSTRAINT fb_reply_boardnum_fk REFERENCES FREE_BOARD (fb_boardnum) ON DELETE CASCADE
 , user_id VARCHAR2(50) CONSTRAINT fb_reply_id_fk REFERENCES MEMBER_TB (user_id)
 , fb_reple_content VARCHAR2(1000) NOT NULL
 , fb_reple_regdate DATE DEFAULT SYSDATE
);

CREATE TABLE LOOKBOOK_BOARD(
 lb_boardnum NUMBER PRIMARY KEY
 , user_id VARCHAR2(50) CONSTRAINT lb_id_fk REFERENCES MEMBER_TB(user_id)
 , lb_title VARCHAR2(100) NOT NULL
 , lb_content VARCHAR2(2000) NOT NULL 
, lb_likes NUMBER DEFAULT 0
 , lb_hitcount NUMBER DEFAULT 0
 , lb_regdate DATE DEFAULT SYSDATE
);

CREATE SEQUENCE lb_seq;

CREATE SEQUENCE lb_seq2;


CREATE TABLE LB_REPLE(
 lb_reple_num NUMBER PRIMARY KEY
 , lb_boardnum NUMBER CONSTRAINT lb_reply_boardnum_fk REFERENCES LOOKBOOK_BOARD (lb_boardnum) ON DELETE CASCADE
 , user_id VARCHAR2(50) CONSTRAINT lb_reply_id_fk REFERENCES MEMBER_TB(user_id)
 , lb_reple_content VARCHAR2(1000) NOT NULL
, lb_reple_regdate DATE DEFAULT SYSDATE

);

CREATE SEQUENCE lb_reple_seq;

CREATE TABLE LINK_TB(
 link_num NUMBER PRIMARY KEY
 , link_add VARCHAR2(1000) DEFAULT NULL
 , lb_boardnum NUMBER CONSTRAINT lb_link_boardnum_fk REFERENCES LOOKBOOK_BOARD (lb_boardnum) ON DELETE CASCADE
);

CREATE SEQUENCE link_seq;

CREATE TABLE TAG_TB(
 tag_num NUMBER PRIMARY KEY
 , tag VARCHAR2(1000) DEFAULT NULL
, lb_boardnum NUMBER CONSTRAINT lb_tag_boardnum_fk REFERENCES LOOKBOOK_BOARD (lb_boardnum) ON DELETE CASCADE
);

CREATE SEQUENCE tag_seq;

CREATE TABLE PIC_TB(
 pic_num NUMBER PRIMARY KEY
 , originalfile VARCHAR2(1000) NOT NULL
 , savedfile VARCHAR2(1000) NOT NULL
, lb_boardnum NUMBER CONSTRAINT lb_pic_boardnum_fk REFERENCES LOOKBOOK_BOARD ON DELETE CASCADE
);

CREATE SEQUENCE pic_seq;

